### ISSUE TITLE
Use `go test` instead of `gb test`

### ISSUE THREAD

**Issue by bahlo** [skizzehq/skizze#132]
Hello,

while I like gb and it's folder structure, I don't like it's testing tool.
What do you think of replacing `gb test` in the Makefile with the Go counterpart?

You could make use of awesome Go testing features, which are not (yet) possible in gb, like `-race` or `-cover`, e.g.:
```Makefile
GOPATH=$(CURDIR):$(CURDIR)/vendor

test:
	GOPATH=$GOPATH go test -v -race -cover ./src/...
```

**Comment by njpatel** [comment]
:+1:

**Comment by seiflotfy** [comment]
:+1:
