### ISSUE TITLE
Add src/storage/test.log to .gitignore

### ISSUE THREAD

**Issue by martinpinto** [skizzehq/skizze#135]
When executing `make test` a log file is created under src/storage/test.log. If uncareful, this file might get committed in a patch.

This file should be added to .gitignore

**Comment by seiflotfy** [comment]
If shouldn't be in the commit to beging with. Also the unit test should avoid creating a test.log in the first place. This is a stupid error in the code (my bad). Anyhow you don't need to put it in .gitignore. If it somehow ends there then you are doing either ``` git add``` which you shouldn't but rather be specific on what you want to add.

Anyhow I fixed it via
