### ISSUE TITLE
Persistence

### ISSUE THREAD

**Issue by seiflotfy** [skizzehq/skizze#92]
Inspired by Redis's http://redis.io/topics/persistence

We should try to have the following per sketch:
* Snapshots: after a given time-interval n or m operations on a sketch.
* AOF: between Snapshots save a log of Add/Remove/Merge operations, which can be replayed back if on top of the last snapshot take, this log has to be cleared as soon as a new Snapshot has been taken.

This has to be running in its own process if possible.
Should the time-interval and threshold be global or sketch specific?

### Snapshot procedure
* lock all sketches from being allowed to do ADD
* save all DEFAULT SETTINGS
* Deep copy all sketches Info
* set up an sqlite db as an AOF ===> one table with timestamp | sketchId | rawMessage (one sqlite since if we have too many AOF's open we will end up dealing with open files limits on unix systems etc...)
* Foreach sketch in sketches:
  * save sketch
  * replay from AOF (SELECT * FROM ops WHERE sketchId = ?)
  * unlock sketch
* Save deep copied sketches info from previously

**Comment by martinpinto** [comment]
I believe it makes more sense to make time-intervals and thresholds sketch specific. You probably need more often to do snapshots for bloom filters than for t-digest. They should also be configurable via config.

**Comment by seiflotfy** [comment]
makes sense to me. I fear however ppl creating 1 GB sketches and expecting with a 1 min snapshot or 1000 operations threshold for it to perform in a timely manner

**Comment by seiflotfy** [comment]
Snapshots on intervals is now implemented with https://github.com/seiflotfy/skizze/pull/94

**Comment by seiflotfy** [comment]
Do we want to keep an AOF per sketch or for all of Skizze:
pros of per sketch:
* resume insertion per sketch as soon as sketch snapshot is taken.
cons:
* Defaults being set on a global skizze level can not be logged properly, would have to cross intersect all ops from all AOFs.

pros for global:
* sequential ops (debugging what hit the API in a sequence)
* easy maintenance due to one file in append only
cons:
* As long as a sketch is being saved no adding will be online

I'd go with the second if you guys don't mind.
