### ISSUE TITLE
Use a build system

### ISSUE THREAD

**Issue by njpatel** [skizzehq/skizze#98]
For people to reliably deploy Skizze we have to make sure that they can build exactly what we release, and for that we need to make sure our external dependancies are locked down.

I suggest we use `gb` (https://getgb.io) because it's super easy to work with, easy to explain, and I've personally had a great experience with it.

While `GO15VENDOREXPERIMENT` is also making it's way down the pipeline, I'd rather not have to think about the build system at all, and let someone else deal with the niggles. `gb` feels like a good choice in this regard.

Thoughts?

**Comment by martinpinto** [comment]
looks good, I like it already +1

**Comment by ronoc** [comment]
:+1:
